### ISSUE TITLE
node js TypeError issue

### ISSUE THREAD

**Issue by sushilr007** [mfix22/gest#8]
When i am testing my app....i am getting error "TypeError: Cannot read property 'operation' of undefined". i have used mocha and node both.

this is my code which is in /test/index.js

const should = require('should');

const zapier = require('zapier-platform-core');

const App = require('../index');
const appTester = zapier.createAppTester(App);

describe('My App', () => {

  it('should load recipes', (done) => {
    const triggerPointer = 'triggers.post';
    const bundle = {
      // NEW CODE
      inputData: {
        style: 'mediterranean'
      }
    };

    appTester(App.triggers.post.operation.perform, bundle)
      .then(results => {
        should(results.length).above(1);

        const firstResult = results[0];
        console.log('test result: ', firstResult)
        should(firstResult.name).eql('name 1');
        should(firstResult.directions).eql('directions 1');

        done();
      })
      .catch(done);
  });

});
describe('My App', () => {

  describe('create recipe create', () => {
    it('should create a new recipe', (done) => {
      const bundle = {
        inputData: {
          name: 'Smith Family Recipe',
          directions: '1. Order out :)',
          authorId: 1
        }
      };

      appTester(App.creates.calendar.operation.perform, bundle)
        .then((result) => {
         result.should.have.property('name');
          done();
        })
        .catch(done);
    });
  });
});

**Comment by mfix22** [comment]
Hey @sushilr007 this is a question that is outside the scope of Gest, but it looks like this is just failing because either`App.create.calendar` or `App.triggers.post` is undefined. Check what you are exporting from `'../index.js'`

**Comment by sushilr007** [comment]
Thank you! Now its working properly.
